<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

	  <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	  <PackageId>SGSFramework.ModulePlugin</PackageId>
	  <Version>1.0.0.12</Version>
	  <Authors>Wayne</Authors>
	  <Company>SHANDA</Company>
	  <Description>動態模組插件套件</Description>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <SignAssembly>True</SignAssembly>
	  <AssemblyOriginatorKeyFile>C:\專案\SES\src\MyModuleKey.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Configurations\appsettings.moduleplugin.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Controllers\Base\" />
    <Folder Include="Systems\Module\Extensions\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\SGSFramework.Core\SGSFramework.Core.csproj" />
    <ProjectReference Include="..\SGSFramework.AuthTokenBucket\SGSFramework.AuthTokenBucket.csproj" />
  </ItemGroup>
	<Target Name="PushToBaGet" AfterTargets="Pack" Condition="'$(Configuration)' == 'Release'">
		<Exec Command="dotnet nuget push &quot;$(ProjectDir)bin\$(Configuration)\*.nupkg&quot; --source http://localhost:5000/v3/index.json --api-key TeamSecret2026_InitialAccess! --allow-insecure-connections --skip-duplicate" />
	</Target>
</Project>
