<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <!-- 設定套件的資訊 -->
	  <PackageId>SGSFramework.AuthTokenBucket</PackageId>
	  <Version>1.0.0.41</Version>
	  <Authors>Wayne</Authors>
	  <Company>SHANDA</Company>
	  <Description>認證與動態限流元件</Description>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <PublishRepositoryUrl>true</PublishRepositoryUrl>
	  <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>
	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
	<Target Name="PushToBaGet" AfterTargets="Pack" Condition="'$(Configuration)' == 'Release'">
		<Exec Command="dotnet nuget push &quot;$(ProjectDir)bin\$(Configuration)\*.nupkg&quot; --source http://localhost:5000/v3/index.json --api-key TeamSecret2026_InitialAccess! --allow-insecure-connections --skip-duplicate" />
	</Target>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	
  <ItemGroup>
    <Content Include="Configurations\appsettings.authtokenbucket.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.19.1" />
    <PackageReference Include="SGSFramework.Core" Version="1.0.0.16" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
  </ItemGroup>

</Project>
