<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <!-- 設定套件的資訊 -->
	  <PackageId>SGSFramework.SystemLog</PackageId>
	  <Version>1.0.0.3</Version>
	  <Authors>Wayne</Authors>
	  <Company>SHANDA</Company>
	  <Description>提供企業內部系統日誌套件。</Description>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <PublishRepositoryUrl>true</PublishRepositoryUrl>
	  <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Abstractions\**" />
    <Compile Remove="Enrichments\**" />
    <EmbeddedResource Remove="Abstractions\**" />
    <EmbeddedResource Remove="Enrichments\**" />
    <None Remove="Abstractions\**" />
    <None Remove="Enrichments\**" />
  </ItemGroup>
	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
	<Target Name="PushToBaGet" AfterTargets="Pack" Condition="'$(Configuration)' == 'Release'">
		<Exec Command="dotnet nuget push &quot;$(ProjectDir)bin\$(Configuration)\*.nupkg&quot; --source http://59.125.142.81:5000/v3/index.json --api-key SHANDA_BaGet_!qaz --allow-insecure-connections --skip-duplicate" />
	</Target>


  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="RazorLight" Version="2.3.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="Serilog.Expressions" Version="5.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="10.0.0" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\..\Shared\SGSFramework.Core\SGSFramework.Core.csproj" />
  </ItemGroup>


</Project>
