<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>C:\專案\SES\src\MyModuleKey.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>


	<ItemGroup>
		<!-- 將 MediatR 標記為 PrivateAssets="All" 或 ExcludeAssets="runtime" 避免輸出至 plugins 目錄 -->
		<PackageReference Include="MediatR" Version="12.0.1" PrivateAssets="All" />
	</ItemGroup>
	
  <ItemGroup>

    <ProjectReference Include="..\..\..\SGS.Modules.ORG.Contracts\SGS.Modules.ORG.Contracts.csproj" />

    <ProjectReference Include="..\..\..\SGSFramework.ReportEngine\SGSFramework.ReportEngine.csproj" />

    <ProjectReference Include="..\Module.ORG.Infrastructure\SGS.Modules.ORG.Infrastructure.csproj" />
  </ItemGroup>



  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="powershell -Command &quot;&amp; { Set-AuthenticodeSignature -FilePath '$(TargetPath)' -Certificate (Get-ChildItem -Path Cert:\CurrentUser\My\DB22B4CE33AE64287F9392F3025EBCB7880BE213) -TimestampServer 'http://timestamp.digicert.com' }&quot;" />
  </Target>

</Project>
