<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	<!-- 加入 NU1900 避免資安警報在 PMC 建置時阻斷指令 -->
	<NoWarn>$(NoWarn);NU1900</NoWarn>
	<!-- 避免未填寫 XML 註解時跳出警告 -->
	<NoWarn>$(NoWarn);1591</NoWarn>
	  <!-- 允許 OpenAPI Source Generator 使用 C# 攔截器功能 -->
  <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.OpenApi.Generated</InterceptorsNamespaces>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<VersionPrefix>2026.08.15.1920</VersionPrefix>

  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\**" />
    <Content Remove="Controllers\**" />
    <EmbeddedResource Remove="Controllers\**" />
    <None Remove="Controllers\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\Enterprise.HttpSdk\Enterprise.HttpSdk.csproj" />
    <ProjectReference Include="..\..\Infrastructure\SGSFramework.ModulePlugin\SGSFramework.ModulePlugin.csproj" />
    <ProjectReference Include="..\..\Modules\ORG\Module.ORG.Infrastructure\SGS.Modules.ORG.Infrastructure.csproj" />
    <ProjectReference Include="..\PhysLIMS.Controller\SGSFramework.ApiInfrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\..\..\..\Users\user\Documents\SQL Server Management Studio 22\PhysLIMSDB_Init.sql" Link="Data\Scripts\PhysLIMSDB_Init.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="logs\" />
  </ItemGroup>

</Project>
